language: c
script: bash -ex .travis-ci.sh
addons:
  apt:
    sources:
      - avsm
    packages:
      - ocaml
      - opam
env:
  - DOWNSTREAM=none
  - DOWNSTREAM=verdi
sudo: false
notifications:
  email: false
