language: c
script: bash -ex .travis-ci.sh
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
      - aspcud
env:
  matrix:
    - DOWNSTREAM=none COQ_VERSION=8.5.3
    - DOWNSTREAM=verdi COQ_VERSION=8.6.1
    - DOWNSTREAM=none COQ_VERSION=8.7.1
sudo: false
notifications:
  email: false
