language: c
script: bash -ex .travis-ci.sh
addons:
  apt:
    sources:
      - avsm
    packages:
      - ocaml
      - opam
      - aspcud
env:
  global:
    - COQ_VERSION=8.5.3
    - MATHCOMP_VERSION=1.6
  matrix:
    - DOWNSTREAM=none
    - DOWNSTREAM=verdi-aggregation
sudo: false
notifications:
  email: false
